name: TownyColonies
version: '${version}'
main: cz.neumimto.towny.townycolonies.TownyColonies
depend: [ Towny ]
authors: [ NeumimTo ]
api-version: 1.19
folia-supported: true
libraries:
    - 'com.electronwill.night-config:hocon:3.6.6'
    - 'com.electronwill.night-config:core:3.6.6'
    - 'com.google.inject:guice:5.1.0'